{
  "Restaurants":
  [
    {"RestName":"Uncle Julio's","RestDescription":"Uncle Julio's on Potomac Town Pl is Woodbridge's go-to spot for fresh, authentic Mexican cuisine. From appetizers to fajitas to desserts and drinks, we use only the best ingredients to ensure you'll enjoy every bite whether you dine-in, carry out, or place an order for delivery.","RestID":1,"RestImage":"https://res.cloudinary.com/unclejulios/image/upload/f_auto,q_auto,w_500/v1605030244/Wordpress/Family-Meals-To-Go_101CR_vtfxqp.jpg","RestCuisine":"Mexican","RestAddress":"14900 Potomac Town Pl #150 Woodbridge, VA 22191","RestHours":"Sun-Thu 11AM-10PM Fri-Sat 11AM-11PM","RestWebsite":"https://unclejulios.com","RestPhone":"703-763-7322","RestPrice":"$$","RestStars":"4.1"},
    {"RestName":"Aroma Latin Fusion","RestDescription":"With the help of a very experienced Peruvian Chef (in Peru) and the hands of a very experienced executive chef in the house, the new Restaurant, AROMA LATIN FUSION, opens its doors to the public presenting a menu full of surprises combining exotic flavors from Colombia and Peru to bring a piece of our native countries to your platter.","RestID":2,"RestImage":"https://aromalatinfusion.com/wp-content/uploads/2020/10/platos-aroma-latin-fusion-3-min.jpg","RestCuisine":"Colombian","RestAddress":"15200 Potomac Town Pl #120 Woodbridge, VA 22191","RestHours":"Sun-Sat 11:30AM-8PM","RestWebsite":"https://aromalatinfusion.com","RestPhone":"571-285-2086","RestPrice":"$$$","RestStars":"4.6"},
    {"RestName":"Burger Fi","RestDescription":"From all-natural Angus Beef free of steroids, additives and hormones, to a chef-driven menu loaded with uncompromising flavors and fresh ingredients, we are redefining how the world eats burgers.","RestID":3,"RestImage":"https://www.burgerfi.com/wp-content/uploads/2022/03/swag-2022.png","RestCuisine":"Burgers","RestAddress":"15202 Potomac Town Pl #105 Woodbridge, VA 22192","RestHours":"Sun-Sat 10:45AM-9PM","RestWebsite":"https://burgerfi.com","RestPhone":"571-402-6789","RestPrice":"$","RestStars":"4.0"},
    {"RestName":"Dak Khao Thai Eatery","RestDescription":"Local fresh Thai Cuisine for everyone. Every dish is crafty made to order using high quality ingredients including locally made fresh noodles, chef's home grown Thai herbs, & Rare-Finds Asian vegetables","RestID":4,"RestImage":"https://static.wixstatic.com/media/66b2ec_536f590d1bab4c8e9d704cfb3c32ee8b~mv2_d_3000_2250_s_2.jpg/v1/fill/w_435,h_490,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/P1017429_edited.jpg","RestCuisine":"Thai","RestAddress":"15200 Potomac Town Pl #110 Woodbridge, VA 22191","RestHours":"Sun-Thurs 11AM-9:30PM Fri & Sat 11AM-10:30PM","RestWebsite":"https://dokkhao.com","RestPhone":"571-285-2459","RestPrice":"$$","RestStars":"4.5"},
    {"RestName":"Firebirds Wood Fired Grill","RestDescription":"We are an American Restaurant and Steakhouse known for our scratch kitchen, bold flavors and inviting atmosphere. Enjoy our signature menu items including hand-cut, aged steaks and fresh seafood or our specialty crafted cocktails and select wines.","RestID":5,"RestImage":"https://firebirdsrestaurants.com/wp-content/uploads/2021/08/three-dish__1080x1080.jpg","RestCuisine":"Steak","RestAddress":"15100 Potomac Town Pl #160 Woodbridge, VA 22191","RestHours":"Sun-Thurs11AM - 10PM Fri & Sat 11AM - 11PM","RestWebsite":"https://woodbridge.firebirdsrestaurants.com","RestPhone":"703-763-5022","RestPrice":"$$","RestStars":"4.4"},
    {"RestName":"Nando's PERi PERi","RestDescription":"Welcome to Nando's. Home of the legendary South African flame-grilled PERi-PERi chicken and sauces.","RestID":6,"RestImage":"https://olo-images-live.imgix.net/ce/ceaeda9b4a1a41348574a531a031512c.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=fill&fm=png32&bg=transparent&s=18b883639591a67a7175cab87ded62e7","RestCuisine":"Chicken","RestAddress":"15001 Potomac Town Pl #150 Woodbridge, VA 22191","RestHours":"Sun-Thurs 10:30AM-10PM Fri & Sat 10:30AM-10:30PM","RestWebsite":"https://nandosperiperi.com","RestPhone":"571-659-6340","RestPrice":"$$","RestStars":"4.4"},
    {"RestName":"Sushi Jin Next Door","RestDescription":"Sushi, udon, sake & other Japanese offerings served in a high-ceilinged space with blond-wood decor.","RestID":7,"RestImage":"http://sushijinnextdoor.com/wp-content/uploads/food-8.jpg","RestCuisine":"Japanese","RestAddress":"14901 Potomac Town Place, Suite 135, Woodbridge, VA 22191","RestHours":"Sun-Thurs 11AM-9:30PM Fri & Sat 12PM-10:30PM","RestWebsite":"http://sushijinnextdoor.com/","RestPhone":"703-670-0461","RestPrice":"$$","RestStars":"4.2"},
    {"RestName":"Korean Grill","RestDescription":"Korean-style BBQ, tofu stews & other hearty, traditional dishes offered in a low-key restaurant.","RestID":8,"RestImage":"https://s3-media0.fl.yelpcdn.com/bphoto/sDwZYnzTa_YIhTM6fmyXTg/o.jpg","RestCuisine":"Korean","RestAddress":"3131 Golansky Blvd Woodbridge, VA 22192","RestHours":"Mon-Sat 11AM-9:00PM Sun Closed","RestWebsite":"https://www.yelp.com/biz/korean-grill-woodbridge?osq=Korean+Bbq","RestPhone":"703-680-3500","RestPrice":"$$","RestStars":"4.7"},
],
  "Status":"OK"
}

